### PR TITLE
ARM's booting sequence ready to merge

### PR DESCRIPTION
**Pull request by davidgao**
Properly tested. Please merge ASAP.

### CODE REVIEW

**Comment by BarclayII** [comment]
Merged

Date: Mon, 28 Sep 2015 05:37:18 -0700

**Comment by BarclayII** [comment]
`sleep()` and `usleep()` is both device-dependent and architecture-dependent.  (e.g. Both MSIM and Loongson only have RTC with second precision, and `usleep()` should be implemented by reading MIPS-specific `COUNT` register in coprocessor)
For that reason, both functions should not be implemented in `drivers` module.
I personally suggest that something like `getsecond()` or `getmicrosecond()` should be implemented in `drivers`, and `sleep()` should be implemented in `arch` directory instead.

**Comment by davidgao** [comment]
well, talking about `sleep()`, it is not _that_ dependent on architecture and device. If we can have functions like `getsec()` and `getusec()` implemented in drivers, the `sleep()` routine would be the same.
ARM's GTC is a counter as well, but we would be reading time or count values anyway.

**Comment by BarclayII** [comment]
What I meant is that RTC (or GTC in your case) may have different precision.

Your GTC have nanosecond-precision so that you can directly perform `sleep()` and `usleep()` by consulting the device.

However, our Loongson boxes and MSIM emulators only have second-precision RTCs, and CPU frequencies have to be determined dynamically by reading both RTC clock and `COUNT` register, which is a **MIPS coprocessor register**.  If we solely rely on RTC driver to perform `sleep()` or `usleep()`, it will be inaccurate or even impossible.  Indeed, we're reading some sort of counters, but there are _counters in peripheral devices_ and _counters in processors_, which should be treated separately (namely, in `drivers` and `arch` directory).

Therefore, even we provide `getsec()` and `getusec()` in drivers, the `sleep()` and `usleep()` implementation may _not_ be necessarily the same, especially when `getusec()` from device driver is unavailable.

We can provide a default `sleep()` and `usleep()` implementation by a `__attribute__((weak))` function.

**Comment by davidgao** [comment]
ok, i get your point. Maybe we can treat this `sleep()` routine in the way we treat drivers in the future. We can make structs containing function pointers and use them like interfaces like

``` C
struct secclock {
    some_time_t (* getsec)(void);
    void (* sleep)(void);
}
```

**Pull request merged**
